runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  AIRPRESS_CONFIG: config/config.yaml

builtins:
- deferred: on

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
- url: /_app/[^/]*/config/
  static_dir: config/assets/
  secure: always
- url: /_app/[^/]*/assets/
  static_dir: dist/
  secure: always
- url: .*
  script: app.main.app
  secure: always

libraries:
- name: endpoints
  version: latest
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: yaml
  version: latest
- name: lxml
  version: latest

skip_files:
- - ^(.*/)?.*~
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?\.DS_Store$
- ^(.*/)?\.gitignore$
- ^\.git/.*
- ^node_modules/.*
- ^htmlcov/.*
- ^env/.*
