#!/bin/sh -e

EMAIL_ADDRESS="$(egrep -o "^service_account:.*" config.yaml | cut -d\" -f2)"
KEY="$(egrep -o "^key:.*" config.yaml | cut -d\" -f2)"

dev_appserver.py \
  --appidentity_email_address $EMAIL_ADDRESS \
  --appidentity_private_key_path $KEY \
  $@ .
