#!/bin/bash -e

#    --nologcapture \
if [ -d env ]; then
  source env/bin/activate
  nosetests \
    -v \
    --rednose \
    --nocapture \
    --with-gae \
    --with-coverage \
    --cover-erase \
    --cover-html \
    --cover-html-dir=htmlcov \
    --cover-package=app \
    app/
  deactivate
else
  echo 'Run ./scripts/setup first.'
  exit 1
fi
